export enum ActionTypes {
    GET_EXCHANGE_RATES = 'GET_EXCHANGE_RATES',
    SET_EXCHANGE_RATES = 'SET_EXCHANGE_RATES',
    CANCEL_EXCHANGE = 'CANCEL_EXCHANGE',
    UPDATE_AMOUNT = 'UPDATE_AMOUNT',
    UPDATE_OUTCOMING_WALLET = 'UPDATE_OUTCOMING_WALLET',
    UPDATE_INCOMING_WALLET = 'UPDATE_INCOMING_WALLET'
}